# code deploy workflow
version: 0.0
os: linux

# giving permission to files and folders to centos user in home directory
files:
  - source: ./
    destination: /home/centos
permissions:
  - object: /home/centos
    owner: centos
    group: centos
    mode: 700
    type:
      - file
  - object: /home/centos
    owner: centos
    group: centos
    mode: 700
    type:
      - directory

hooks:
  ApplcationStop:
    - location: ./applicationStop.sh
      timeout: 300

  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 300

  ApplicationStart:
    - location: ./applicationStart.sh
      timeout: 300