# code deploy workflow
version: 0.0
os: linux

# giving permission to files and folders to centos user in home directory
files:
  - source: ./webapp/recipe/target/recipe.war
    destination: /opt/tomcat/webapps/

hooks:
  BeforeInstall:
    - location: ./infrastructure/aws/codedeploy/beforeInstall.sh
      timeout: 300

  AfterInstall:
    - location: ./infrastructure/aws/codedeploy/afterInstall.sh
      timeout: 300

  ApplicationStart:
    - location: ./infrastructure/aws/codedeploy/applicationStart.sh
      timeout: 300