version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip -y
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
      - run:
          name: Run unit tests
          command: |
            export LOGGING_FILE_NAME=recipe.log
            cd webapp/recipe
            mvn clean test
      - run:
          name: Build war
          command: |
            export LOGGING_FILE_NAME=recipe.log
            cd webapp/recipe
            mvn install -DskipTests
      - run:
          name: Build Deployment Artifact
          command: |
            pwd
            mkdir codedeploy_artifact
            zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip webapp/recipe/target/ROOT.war infrastructure/aws/codedeploy/*.sh appspec.yml
            pwd
            ls -al
            mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            cd codedeploy_artifact
            ls -al
      - run:
          name: Copy Artifact to S3
          command: aws s3 cp codedeploy_artifact/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip s3://${S3_CODEDEPLOY_BUCKET}/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
      - run:
          name: CodeDelopy API Call
          command: |
            aws deploy create-deployment \
              --application-name "csye6225-webapp" \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              --deployment-group-name "csye6225-webapp-deployment" \
              --description "CSYE6225 - Codedeploy" \
              --s3-location bucket=${S3_CODEDEPLOY_BUCKET},key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip,bundleType=zip \
              --region us-east-1 \
              --output json
workflows:
  version: 2
  setup_and_build:
    jobs:
      - build
